import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Bell, Settings } from 'lucide-react';
import Link from 'next/link';
import { jaJP } from '@clerk/localizations';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        // variables: { colorPrimary: 'blue' },
      }}
      localization={jaJP}
    >
      <html lang="ja" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="min-h-screen bg-zinc-950 text-zinc-200">
            {/* ヘッダー */}
            <header className="sticky top-0 p-4">
              <div className="container mx-auto">
                <Card className="backdrop-blur-sm bg-zinc-900/50 border-zinc-800 rounded-lg shadow-lg shadow-zinc-900/20">
                  <div className="px-4">
                    <div className="grid grid-cols-12 h-14 items-center">
                      {/* ロゴエリア */}
                      <div className="col-span-4">
                        <Link
                          href="/"
                          className="flex items-center gap-2 hover:opacity-80 transition-opacity"
                        >
                          <div className="w-8 h-8 bg-indigo-500 rounded-md"></div>
                          <span className="font-bold text-lg text-zinc-100">
                            Logo
                          </span>
                        </Link>
                      </div>

                      {/* 中央スペース */}
                      <div className="col-span-4"></div>

                      {/* ナビゲーション */}
                      <div className="col-span-4">
                        <nav className="flex justify-end items-center gap-4">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800"
                          >
                            <Bell size={20} />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800"
                          >
                            <Settings size={20} />
                          </Button>
                          <SignedOut>
                            <SignInButton />
                          </SignedOut>
                          <SignedIn>
                            <UserButton />
                          </SignedIn>
                        </nav>
                      </div>
                    </div>
                  </div>
                </Card>
              </div>
            </header>

            {/* スクロールテスト用セクション */}
            <main className="container mx-auto px-4 space-y-8">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
